### ISSUE TITLE
能配几张图展示下vim配置吗?

### ISSUE THREAD

**Issue by rockliuxn** [hotoo/vimrc#5]
你好!  能配几张图展示下vim配置吗?  这样更加直观一些,  谢谢!

**Comment by hotoo** [comment]
一个 Vim 配置并不适用每个人，你应该查看其他人的 vimrc 并从中获取自己需要的部分。

截图好像并没有什么意义，基本就是标准的 Vim 界面 + 一些插件，使用这个 vimrc 配置后的使用手册倒是有点价值，我看什么时候高兴再考虑写个使用手册吧。

**Comment by rockliuxn** [comment]
@hotoo  感谢你的分享, 期待你的使用手册!
