### ISSUE TITLE
vim 路径自动补全

### ISSUE THREAD

**Issue by guoshencheng** [hotoo/vimrc#6]
hi！我其实自己有在日常开发中使用vim作为编辑器。虽然中途尝试使用atom安装vim快捷键代替，现在想用回vim，但是用了atom有段时间之后觉得他有个`https://atom.io/packages/autocomplete-paths`的插件用起来还是很舒服的，可以模糊的查询文件并补全路径，不知道vim下有没有相似的插件或者配置

**Comment by guoshencheng** [comment]
自己解决了一下，使用`fzf.vim`简单的做到了这个功能，使用
```
:imap <c-x><c-f> <plug>(fzf-complete-path)
```
就能简单的实现路径的模糊匹配，我现在的选择是再加上`fd`，使用`fd`会比`find`更加友好
```
:inoremap <expr> <c-x><c-f> fzf#complete('fd -t f')
```
下一步的话，考虑看看能不能`YCM`结合一下吧

**Comment by guoshencheng** [comment]
@hotoo 很早因为这个vimrc关注到您，因为没有其他联系方式提问所以在这里想请教一下，现在问题解决了还是很开心的，我自己把issue关掉

**Comment by hotoo** [comment]
确实挺好的编辑体验，赞。期待和 YCM 结合的方案。

- https://www.reddit.com/r/vim/comments/7t5yug/is_there_an_autocompletepaths_equivalent_for_vim/
- https://codeyarns.com/2016/10/06/how-to-autocomplete-path-in-vim-insert-mode/
