### ISSUE TITLE
vim报错

### ISSUE THREAD

**Issue by king-bcolor** [hotoo/vimrc#8]
试过好多个vimrc配置，经常报错“
第    1 行:
E492: 不是编辑器的命令: intainer:
第  407 行:
E121: 未定义的变量: a:direction
E15: 无效的表达式: a:direction == 'gv'
第  413 行:
E121: 未定义的变量: l:pattern
E15: 无效的表达式: l:pattern
第  414 行:
E121: 未定义的变量: l:saved_reg
E15: 无效的表达式: l:saved_reg
第  415 行:
E193: :endfunction 不在函数内
处理 /root/.vimrc 时发生错误:
第    1 行:
E492: 不是编辑器的命令: et number
请按 ENTER 或其它命令继续”

不是很影响具体使用，但看着很难受

**Comment by hotoo** [comment]
不知道你怎么使用的，请提供详细步骤。

**Comment by king-bcolor** [comment]
> 不知道你怎么使用的，请提供详细步骤。

放弃配置vim了，用nano了 :joy:
